# Generated by Django 5.0.2 on 2024-03-08 19:16

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('execl_file', models.FileField(upload_to='execl_files/%y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SendSmsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True)),
                ('execl_file', models.FileField(upload_to='execl_files/%y/%m/%d')),
                ('message_body', models.TextField(verbose_name='متن پیام')),
                ('send_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='از کاربر')),
                ('to_mobile_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_file', to='sms.uploadfilemodel', verbose_name='به شماره همراه')),
            ],
            options={
                'verbose_name': 'send sms',
                'verbose_name_plural': 'send_sms',
                'db_table': 'send_sms',
            },
        ),
    ]
