# Generated by Django 5.0.2 on 2024-03-25 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendsinglemessagemodel',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='sendsinglemessagemodel',
            name='foreignkey_mobile_phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreignkey_mobile_phone', to='sms.phonebookmodel', verbose_name='انتخاب شماره موبایل'),
        ),
    ]
