# Generated by Django 5.0.2 on 2024-03-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsinglemessagemodel',
            name='to_mobile_phone',
            field=models.CharField(max_length=15, verbose_name='به شماره همراه'),
        ),
    ]
