# Generated by Django 5.0.2 on 2024-03-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmultiplesmessagemodel',
            old_name='foreignkey_mobile_phone',
            new_name='m2m_mobile_phone',
        ),
        migrations.AddField(
            model_name='phonebookmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
