# Generated by Django 5.0.2 on 2024-03-24 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_sendsinglemessagemodel_to_mobile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendsinglemessagemodel',
            name='foreignkey_mobile_phone',
        ),
        migrations.RemoveField(
            model_name='sendsinglemessagemodel',
            name='send_time',
        ),
        migrations.RemoveField(
            model_name='sendsinglemessagemodel',
            name='title_message',
        ),
    ]
