# Generated by Django 5.0.2 on 2024-03-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_remove_sendsinglemessagemodel_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmultiplesmessagemodel',
            old_name='m2m_mobile_phone',
            new_name='mobile_phones',
        ),
        migrations.RemoveField(
            model_name='sendmultiplesmessagemodel',
            name='is_active',
        ),
    ]
