# Generated by Django 5.0.2 on 2024-03-24 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_remove_sendsinglemessagemodel_foreignkey_mobile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendsinglemessagemodel',
            name='to_mobile_phone',
        ),
        migrations.AddField(
            model_name='sendsinglemessagemodel',
            name='foreignkey_mobile_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foreignkey_mobile_phone', to='sms.phonebookmodel'),
        ),
    ]
