# Generated by Django 5.0.2 on 2024-04-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_sendsinglemessagemodel_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsinglemessagemodel',
            name='from_user',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
