# Generated by Django 5.0.2 on 2024-03-24 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_remove_sendsinglemessagemodel_to_mobile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmultiplesmessagemodel',
            name='send_time',
        ),
        migrations.RemoveField(
            model_name='sendmultiplesmessagemodel',
            name='title_message',
        ),
    ]
