# Generated by Django 5.0.2 on 2024-03-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_remove_sendmultiplesmessagemodel_send_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmultiplesmessagemodel',
            name='m2m_mobile_phone',
            field=models.ManyToManyField(related_name='m2m_mobile_phones', to='sms.phonebookmodel'),
        ),
    ]
