# Generated by Django 5.0.2 on 2024-04-04 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_alter_sendsinglemessagemodel_from_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsinglemessagemodel',
            name='from_user',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender_single_sms', to=settings.AUTH_USER_MODEL, verbose_name='از کاربر'),
        ),
    ]
