# Generated by Django 5.0.2 on 2024-04-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_alter_sendsinglemessagemodel_from_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendsinglemessagemodel',
            old_name='foreignkey_mobile_phone',
            new_name='to_user',
        ),
    ]
