# Generated by Django 5.0.2 on 2024-03-08 19:27

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2024, 3, 8, 19, 27, 46, 987623, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
