# Generated by Django 5.0.2 on 2024-03-25 00:02

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2024, 3, 25, 0, 2, 37, 449610, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
