# Generated by Django 5.0.2 on 2024-03-03 23:04

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True)),
                ('code', models.PositiveSmallIntegerField()),
                ('time_validity', models.DurationField()),
            ],
            options={
                'verbose_name': 'otp code',
                'verbose_name_plural': 'otp codes',
                'db_table': 'otp_code',
            },
        ),
    ]
