# Generated by Django 5.0.2 on 2024-03-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='time_validity',
            field=models.TimeField(),
        ),
    ]
