# Generated by Django 5.0.2 on 2024-04-04 17:25

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2024, 4, 4, 17, 25, 6, 593236, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
