# Generated by Django 5.0.2 on 2024-04-04 21:25

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2024, 4, 4, 21, 25, 29, 566453, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
